### ISSUE TITLE
1.3-series releases?

### ISSUE THREAD

**Issue by jeffb4** [docker/containerd-packaging#147]
I am missing some of the features added to the 1.3-series of containerd releases. While this repository probably works fine to build such using the `make REF=${TAG}` functionality and I'll be testing such shortly, is there a path forward for 1.3 releases to get distro builds?

My apologies if this is a dup, I couldn't find any old issues about it.

**Comment by thaJeztah** [comment]
Thanks for opening; let me close this ticket, as we're currently shipping containerd 1.6 now (LTS release of containerd)
