### ISSUE TITLE
Add ppc64le to packages

### ISSUE THREAD

**Issue by carlosedp** [docker/containerd-packaging#164]
Possible to add ppc64le architecture to the centos, fedora, ubuntu and debian distros?

Is this a matter of adding to the Jenkinsfile matrix? Are there ppc64le builders available or is it crossbuilt?

**Comment by thaJeztah** [comment]
The list of architectures in this repository is what's being tested on pull requests in this repository; the actual release pipeline is currently internal (in a private repository at docker) and defines the matrix of distros / architectures that are _published_.

For ppc64le and s390x, Docker has a partnership with IBM, who builds packages for those platforms now; those packages can be found now on download.docker.com, e.g. https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/ppc64el/


Let me close this ticket for housekeeping 👍
