### ISSUE TITLE
Consider validating and building against Ubuntu 20.10 "Groovy Gorilla"

### ISSUE THREAD

**Issue by DeeDeeG** [docker/containerd-packaging#197]
Hi folks.

Ubuntu 20.10 "Groovy Gorilla" is scheduled to be released on October 22nd.
https://discourse.ubuntu.com/t/groovy-gorilla-release-schedule/15531

It might be nice to get "ahead of the curve," with packages ready to go for when the new distribution release comes out.

Thanks for considering.

\- DeeDeeG

**Comment by thaJeztah** [comment]
Let me close this one, as groovy was added (but has been removed since then, as it reached EOL)
