### ISSUE TITLE
Add Ubuntu 22.04 "Jammy Jellyfish" on CI/CD

### ISSUE THREAD

**Issue by julian-alarcon** [docker/containerd-packaging#262]
Related to https://github.com/docker/for-linux/issues/1345

**Comment by Romain-Geissler-1A** [comment]
The latest release 20.10.13 is available for Jammy since a few days.

**Comment by thaJeztah** [comment]
yes, looks like this can be closed since https://github.com/docker/containerd-packaging/pull/271
