### ISSUE TITLE
include `nerdctl`

### ISSUE THREAD

**Issue by jcpunk** [docker/containerd-packaging#319]
It would be nice if the `nerdctl` utility was available with these packages.

**Comment by thaJeztah** [comment]
Thanks for opening this ticket.

`nerdctl` is a separate project from containerd, and is not an essential component for it (containerd itself is a runtime to be used for other products, such as kubernetes, nerdctl, docker).

The main purpose of this repository is to build the  `containerd.io` packages that we distribute at download.docker.com. Those packages are meant to support the docker engine (`docker-ce`) which uses containerd as runtime. This repository is open-source as it may be useful to others if they want to build containerd.io packages for distros that docker doesn't provide packages for, but the scope of the scripts in this repository is still to build packages  to assist docker-ce / docker engine.


I'm closing this ticket for the reason above, but feel free to fork the repository to modify the code for your own purpose if needed. General contributions to improve the code in this repository (within scope of its purpose) are also still appreciated.


Closing this ticket, but feel free to continue the conversation 👍
