### ISSUE TITLE
containerd 1.6.30 released

### ISSUE THREAD

**Issue by RichieFrame** [docker/containerd-packaging#346]
A containerd update was released yesterday which addresses multiple Go CVEs:

https://github.com/containerd/containerd/releases/tag/v1.6.30

https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg

**Comment by thaJeztah** [comment]
Yes, we're planning to package v1.6.30; we're looking into some issues for the arm 32-bit builds, which may need changes in the build scripts. In the meantime, you could build packages for your distro using the instructions in the readme; https://github.com/docker/containerd-packaging?tab=readme-ov-file#usage


For example, to build packages for ubuntu:24.04;


```bash
make REF=v1.6.30 docker.io/library/ubuntu:24.04
```

After the build completed, you'll find packages in the `build` directory;

```bash
tree build
build
└── ubuntu
    └── jammy
        └── arm64
            └── containerd.io_1.6.30-1_arm64.deb

4 directories, 1 file
```

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/containerd-packaging/pull/347
