### ISSUE TITLE
Add libseccomp-devel for oraclelinux packages

### ISSUE THREAD

**Issue by seemethere** [docker/containerd-packaging#42]
Needed for containerd starup

**Comment by thaJeztah** [comment]
libseccomp-devel is in the spec; https://github.com/docker/containerd-packaging/blob/d1263dc2eec8dfa88a8c18a570cf2bacf771fe61/rpm/containerd.spec#L66

and libseccomp (runtime requirement) was added in https://github.com/docker/containerd-packaging/commit/101a1f8207b9a34e7eeef6d4af00a1d224e9d0a9 (https://github.com/docker/containerd-packaging/pull/157)
