### ISSUE TITLE
containerd.io package missing containerd-shim-runc-v1

### ISSUE THREAD

**Issue by andrewhsu** [docker/containerd-packaging#60]
This may need to be addressed before the `docker/containerd-packaging` is made public.

from a slack conversation with `akihirosuda`:
> containerd.io pkg seems lacking /usr/bin/containerd-shim-runc-v1 (which is not needed for Docker 18.09 though)

**Comment by thaJeztah** [comment]
fixed by https://github.com/docker/containerd-packaging/pull/146

**Comment by bikrambox** [comment]
I found that When Re-installing **docker** in AWS Amazon Linux 2 it just reinstalled Docker but when Installing Fresh Docker all Other dependencies Like **contained, runc** are installed with Docker, Therefore, Reinstallaling **containerd** resolved all the issues. 


`sudo yum reinstall containerd docker -y`


This will resolve it. No need to Copy-Paste them ( i.e. `cp containerd-shim-runc-v1 containerd-shim-runc-v2` )
